### ISSUE TITLE
是不是失效了？

### ISSUE THREAD

**Issue by 5536086** [lzkgbld/porhub#1]
windows下在程序目录运行python main.py没反应，所有环节和mysql都装好了

**Comment by lzkgbld** [comment]
请问您是否修改了configure里面文件，如果是爬收藏夹的内容的话应该是可以的，至于正常分类的还有会员项目我暂时没办法测试了，这是我上个月还有P站会员的时候写的规则，可能会员那边规则又改了...如果您方便，麻烦使用pychars这些工具开一下debug看看报错内容是什么！感谢。

**Comment by lzkgbld** [comment]
如果您不回复我这边先关闭该单据了，如果您还有什么问题可以随时打开。
